# Run 'bundle exec jekyll serve' again if you change this file.

# Site settings
title: Home page
author: Phil Garner
# email: Phil.Garner@idiap.ch
description: >
  Pages containing information about my work, publications and software.

# baseurl: ""
# url: "http://idiap.ch"
twitter_username: philipngarner
github_username:  pgarner

# Build settings
markdown: kramdown
theme: minima

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment this and
# add the path to the pages in order as they should show up
header_pages:
 - talks.md
 - english.md
 - positions.md
 - blog.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
